steps:
  - id: "branch name"
    name: "alpine"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        echo "***********************"
        echo "$BRANCH_NAME"
        echo "***********************"

  # [START tf-init]
  - id: "tf init"
    name: "hashicorp/terraform:0.13.5"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        if [ -d "$$ENV_ROOT/$_BUILD_ENV/" ]; then
          cd $$ENV_ROOT/$_BUILD_ENV
          terraform init || exit 1
        else
          echo "***************************** SKIPPING INIT ************************************"
          echo "$$ENV_ROOT/$BRANCH_NAME folder not found in branch '$BRANCH_NAME'."
          echo "$$ENV_ROOT/$_BUILD_ENV folder not found in branch '$BRANCH_NAME'."
          echo "********************************************************************************"
          exit 1
        fi
  # [END tf-init]
  # [START tf-validate]
  - id: "tf validate"
    name: "hashicorp/terraform:0.13.5"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        if [ -d "$$ENV_ROOT/$_BUILD_ENV/" ]; then
          cd $$ENV_ROOT/$_BUILD_ENV
          terraform validate
        else
          echo "***************************** SKIPPING VALIDATE ************************************"
          echo "$$ENV_ROOT/$BRANCH_NAME folder not found in branch '$BRANCH_NAME'."
          echo "$$ENV_ROOT/$_BUILD_ENV folder not found in branch '$BRANCH_NAME'."
          echo "********************************************************************************"
          exit 1
        fi
  # [END tf-validate]
  # [START tf-plan]
  - id: "tf plan"
    name: "hashicorp/terraform:0.13.5"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        if [ -d "$$ENV_ROOT/$_BUILD_ENV/" ]; then
          cd $$ENV_ROOT/$_BUILD_ENV
          terraform plan
        else
          echo "***************************** SKIPPING PLAN ************************************"
          echo "$$ENV_ROOT/$BRANCH_NAME folder not found in branch '$BRANCH_NAME'."
          echo "$$ENV_ROOT/$_BUILD_ENV folder not found in branch '$BRANCH_NAME'."
          echo "********************************************************************************"
          exit 1
        fi
  # [END tf-plan]
  # [START tf-apply]
  - id: "tf apply"
    name: "hashicorp/terraform:0.13.5"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        if [ -d "$$ENV_ROOT/$BRANCH_NAME/" ] && [ "$$ENV_ROOT/$BRANCH_NAME/" == "$$ENV_ROOT/$_BUILD_ENV/" ]; then
          cd $$ENV_ROOT/$BRANCH_NAME
          terraform apply -auto-approve
        else
          echo "***************************** SKIPPING APPLYING *******************************"
          echo "Branch '$BRANCH_NAME' does not represent an official environment."
          echo "*******************************************************************************"
        fi
# [END tf-apply]
options:
  env:
    - 'ENV_ROOT=infrastructure/gcp/environments'